---
- name: This play will install apache web servers on all the hosts
  hosts: all
  become: yes
  tasks:
    - name: Task1 will install apache2 using apt
      apt:
        name: apache2
        update_cache: yes
        state: latest
    - name: Task2 will upload custom index.html into all hosts
      copy:
        src: "/home/cloudthatoct_51abc8d3_384e_49b9_/playbook-lab/index.html"
        dest: "/var/www/html/index.html"
    - name: Task3 will setup attributes for file
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0644
    - name: Task4 will start apache2
      service:
        name: apache2
        state: started
